name: "Forrest Spotify Curator"
description: "curate playlist based on if it's in-tune."
version: "0.0.4"
slug: "forrest_curator"
ports:
  5000/tcp: 5000
homeassistant_api: true
hassio_api: true
hassio_role: manager
arch:
  - aarch64
schema:
  spotify_client_id: str
  spotify_client_secret: str
  spotify_playlist_id: str
