name: "Forrest Spotify Curator"
description: "curate playlist based on if it's in-tune."
version: "0.0.8"
slug: "forrest_curator"
ports:
  5000/tcp: 5000
arch:
  - aarch64
schema:
  spotify_client_id: str
  spotify_client_secret: str
  spotify_playlist_id: str
