name: "Fitbit Data"
description: "Get timeseries fitbit data."
version: "0.0.5"
slug: "fitbit_data"
ports:
  5000/tcp: 5000
homeassistant_api: true
hassio_api: true
arch:
  - aarch64
schema:
  fitbit_client_id: str
  fitbit_client_secret: str
