name: "Keys to Lights"
description: "Keys to Lights for spotify."
version: "0.0.2"
slug: "spotify_lights"
ports:
  5000/tcp: 5000
homeassistant_api: true
hassio_api: true
hassio_role: manager
services:
  - light
arch:
  - aarch64
schema:
  spotify_client_id: str
  spotify_client_secret: str
